//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestellDetails
    {
        public int Id { get; set; }
        public int BestellId { get; set; }
        public int ArtikelId { get; set; }
        public double Anzahl { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual Bestellungen Bestellungen { get; set; }
    }
}
